language: node_js
branches:
  only: master
node_js: '4.1'
sudo: false
before_deploy:
- openssl aes-256-cbc -K $encrypted_7adcd9f8e90f_key -iv $encrypted_7adcd9f8e90f_iv
  -in id_rsa.enc -out deployKey -d
- echo -e "Host "$DEPLOY_HOST"\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- mv deployKey ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST
      "cd $DEPLOY_PATH && git checkout . && git pull -f origin master"
    on:
      branch: master

script: npm test
