language: node_js
branches:
  only: master
node_js: '0.10'
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_7adcd9f8e90f_key -iv $encrypted_7adcd9f8e90f_iv
  -in id_rsa.enc -out deployKey -d
- echo -e "Host "$DEPLOY_HOST"\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- npm install -g bower
- npm install
- bower install
after_success:
- mv deployKey ~/.ssh/id_rsa
- chmod 600 ~/.ssh/id_rsa
- git remote add deploy ssh://$DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PORT$DEPLOY_PATH/production/web.git
- git push deploy
script: npm test
